# Generated by Django 3.2.8 on 2021-10-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
