# Generated by Django 3.2.8 on 2021-10-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20211028_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='question_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
