# Generated by Django 3.2.8 on 2021-10-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211028_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='type',
            new_name='inbox_type',
        ),
    ]
