# Generated by Django 3.2.8 on 2021-10-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_type_inboxitem_inbox_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='question_title',
            new_name='target_question',
        ),
    ]
