# Generated by Django 3.2.8 on 2021-10-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_question_title_inboxitem_target_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='target_question',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
    ]
