# Generated by Django 3.2.8 on 2021-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_inboxitem_target_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
